  // "dependencies": {
  //   // "@open-wc/webpack-import-meta-loader": "^0.4.1",
  //   // "babel-polyfill": "^6.26.0",
  //   // "babel-preset-env": "^1.7.0",
  //   // "babel-register": "^6.26.0",
  //   // "cookie-parser": "1.4.*",
  //   // "express": "4.17.*",
  //   "karma": "^4.4.1",
  //   // "karma-static": "^1.0.1",
  //   // "karma-webpack": "^5.0.0-alpha.3.0",
  //   "lit-element": "2.2.*",
  //   // "lit-html": "1.1.*",
  //   // "mysql": "^2.17.1",
  //   // "node-fetch": "2.6.*",
  //   // "uuid": "3.3.*",
  //   // "webpack": "^4.41.5"
  // },
  // "devDependencies": {
  //   // "@commitlint/cli": "^8.3.5",
  //   // "@commitlint/config-conventional": "^8.3.4",
  //   "@open-wc/building-rollup": "^0.19.1",
  //   // "@open-wc/eslint-config": "^2.0.2",
  //   "@open-wc/prettier-config": "^0.1.13",
  //   "@open-wc/testing": "^2.5.0",
  //   "@open-wc/testing-karma": "^3.2.30",
  //   // "chai": "^4.2.0",
  //   // "chalk": "3.0.0",
  //   "concurrently": "^5.0.2",
  //   "cross-env": "6.0.3",
  //   "es-dev-server": "^1.36.2",
  //   "eslint": "6.8.0",
  //   // "eslint-plugin-no-only-tests": "^2.4.0",
  //   "eslint-plugin-sonarjs": "^0.5.0",
  //   // "fs-extra": "8.1.0",
  //   // "glogg": "1.0.2",
  //   // "gulp": "^4.0.2",
  //   // "gulp-eslint": "^6.0.0",
  //   // "husky": "^4.0.10",
  //   // "koa-proxies": "0.9.0",
  //   "lint-staged": "^9.5.0",
  //   // "mocha": "7.0.0",
  //   // "npm-check": "5.9.0",
  //   "npm-watch": "0.6.0",
  //   // "prompt": "1.0.0",
  //   // "rimraf": "^3.0.0",
  //   // "rmfr": "^2.0.0",
  //   // "rollup": "^1.29.0",
  //   // "sinon": "^8.1.0",
  //   // "sinon-chai": "^3.4.0",
  //   // "sonarjs": "^1.0.0",
  //   "webpack-merge": "^4.2.2",
  //   // "yargs": "15.1.0"
  // },